// auto-generated by scripts/update-dependencies.ts -- DO NOT EDIT OR DELETE!
export const DEPENDENCIES = {
    "@biomejs/biome": "2.3.4",
    "@eslint/js": "^9.39.1",
    "@types/node": "^24.10.0",
    "discord.js": "^14.24.2",
    dotenv: "^17.2.3",
    eslint: "^9.39.1",
    prettier: "^3.6.2",
    sunar: "^0.7.3",
    tsdown: "^0.16.1",
    tsx: "^4.20.6",
    typescript: "^5.9.3",
    "typescript-eslint": "^8.46.3",
} as const;
