import { $ } from "bun";
import { green, red } from "colorette";

import { DEPENDENCIES } from "../src/utils/dependencies";

const OUTPUT_PATH = "src/utils/dependencies.ts";
const NO_CARET_FILES = ["@biomejs/biome"];

const newDependencies = {};

for (const [dependency, currentVersion] of Object.entries(DEPENDENCIES)) {
    const latestVersion = await $`bun info ${dependency} version`.quiet();
    const newVersion = latestVersion.text().replace(/\n/g, "").trim();
    const formattedVersion = `${NO_CARET_FILES.includes(dependency) ? "" : "^"}${newVersion}`;

    const order = Bun.semver.order(currentVersion, formattedVersion);

    if (order === 0) {
        console.log(`Skipping ${dependency} as it's already up to date`);
    } else {
        console.log(`Updating ${dependency} from ${red(currentVersion)} to ${green(formattedVersion)}`);
    }
    newDependencies[dependency] = formattedVersion;
}

console.log("\nDependencies table");
console.table(newDependencies);

const file = Bun.file(OUTPUT_PATH);
const fileContent = `// auto-generated by scripts/update-dependencies.ts -- DO NOT EDIT OR DELETE!
export const DEPENDENCIES = ${JSON.stringify(newDependencies)} as const;`;

await file.write(fileContent);

await $`biome format --write ${OUTPUT_PATH}`.quiet();

console.log("\nDependencies updated successfully!");
